language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - composer self-update
  - composer install

script: ./vendor/bin/pho -a --reporter spec
